version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: esgualberto/nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: esgualberto/node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s node index.js
    volumes:
      - ./src:/usr/src/app
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - mysql
