FROM golang:alpine as builder 

RUN apk add --no-cache git bash

RUN git clone https://github.com/eduardo-gualberto/fullcycle-docker.git fc-docker

RUN cd fc-docker/desafio-go/src \
    && go build hello.go \
    && mv hello /

FROM alpine 
COPY --from=builder /hello . 
